### ISSUE TITLE
Incompatible library version

### ISSUE THREAD

**Issue by vincentcp** [JuliaApproximation/FastTransforms.jl#106]
Precompiling latest version of FastTransforms does not succeed because of incompatible library (see below) on MacOS.

InitError: could not load library ".julia/artifacts/3677b4b693751024a0923d9e7c6d56da89f15b8e/lib/libgmpxx.4.dylib"
dlopen(.julia/artifacts/3677b4b693751024a0923d9e7c6d56da89f15b8e/lib/libgmpxx.4.dylib, 1): Library not loaded: @rpath/libgmp.10.dylib
Reason: Incompatible library version: libgmpxx.4.dylib requires version 15.0.0 or later, but libgmp.dylib provides version 14.0.0

**Comment by MikaelSlevinsky** [comment]
Cool error message! I'll look into this further, but for the moment does pinning GMP_jll at version 6.1.2 fix it for you temporarily?

**Comment by MikaelSlevinsky** [comment]
Seems like the relevant issue is https://github.com/JuliaRegistries/General/pull/16517. You must be using a very recent version of Julia, say nightly? I'm using 1.3.1 so I can't even pin `GMP_jll` to version 6.2 as it appears you have above (given the artifact SHA https://github.com/JuliaBinaryWrappers/GMP_jll.jl/blob/f6b8e1ef962610c5ffbf27ee509450bca957e94b/Artifacts.toml#L171).

**Comment by vincentcp** [comment]
Yes, the solution you suggested fixed the issue, but not only temporarily. 

I had the issue using Julia 1.3.0 and installed the newest stable release today (1.4.1) to see if it would help in any way since I am not yet familiar with artifacts.

The error message above was indeed made with the new version of Julia, but I got a similar one in 1.3.0. 

I think, this comment can be closed, since after pinning and freeing the artifact I am not able to reproduce this error. Not in 1.3.0 and not in 1.4.1, and not with any combination of `up` `resolve` `pin` and `free`.

The PR to `General` two hours ago must have done the trick. 
Thank you!

**Comment by MikaelSlevinsky** [comment]
> The PR to General two hours ago must have done the trick.

I think so!
