### ISSUE TITLE
Auto-diff + FastTransforms.jl?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastTransforms.jl#119]
How should we support auto-diff (DualNumbers.jl, ForwardDiff.jl, Zygote.jl)? For forward diff should be easy if we add DualNumbers.jl and ForwardDiff.jl as dependencies, but maybe that's autokill.

Perhaps we make another package AutoDiffFastTransforms.jl for this?

**Comment by MikaelSlevinsky** [comment]
Different package. I'm always looking for ways to remove dependencies to keep add/build times stable.
