### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by ranocha** [JuliaApproximation/FastTransforms.jl#121]
I noticed that this repo still uses travic-ci.org, at least based on the badge in the README. travis-ci.org will be shut down at the end of the year, cf. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom. Hence, everything should be migrated to travis-ci.com.

The same is probably true for other repos of JuliaApproximation.

**Comment by MikaelSlevinsky** [comment]
This repository has migrated https://github.com/JuliaApproximation/FastTransforms.jl/commit/da2fb36afeb50770d4d969d718b963df2d174b41
