### ISSUE TITLE
Generalized Zernike polynomials?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastTransforms.jl#124]
Is it possible to transform to Generalized Zernike polynomials orthogonal w.r.t. `(1-r^2)^μ`? The basis is I think
```julia
r^m * P^(μ,|m|)(2r^2-1) * exp(im*m*θ)
```

@MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
Closed in #125.
