### ISSUE TITLE
How to do (complex) spherical harmonics transform?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastTransforms.jl#130]

**Comment by MikaelSlevinsky** [comment]
If you want real longitudinal basis + complex coefficients, use plan_sph2fourier. The execution dispatches on number type, but the plan has real T.

If you want complex longitudinal basis (Laurent) + complex coefficients, use plan_spinsph2fourier with spin 0.

Laurent + real coefficients? Convert coefficients to complex. Is this one supported?

**Comment by dlfivefifty** [comment]
Ah I see. Is it weird that `plan_spinsph2fourier` uses cos and sin for the analysis instead of exp?

**Comment by dlfivefifty** [comment]
nah somethings wrong, maybe with the FastTransforms documentation and you actually mean `plan_sinsph2fourier` maps to complex exp. The following would need to have conjugate symmetry:
```julia
julia> P = plan_spinsph2fourier(Complex{Float64}, 2, 3)
FastTransforms Spin-weighted spherical harmonic--Fourier plan for 2×3-element array of Complex{Float64}

julia> P \ [1.0+0im 2. 3.; 4. 0. 0.]
2×3 Array{Complex{Float64},2}:
  1.1547+0.0im  2.82843+0.0im  4.24264+0.0im
 4.13118+0.0im      0.0+0.0im      0.0+0.0im
```
and the following would give a real-valued matrix:
```julia
julia> P * [1. 2+im 2-im; 4. 0 0]
2×3 Array{Complex{Float64},2}:
 0.866025+0.0im  1.41421+0.707107im  1.41421-0.707107im
  3.87298+0.0im      0.0+0.0im           0.0+0.0im
```

**Comment by MikaelSlevinsky** [comment]
Ok, so I don't think there's anything wrong, *per se*, but I forgot to mention that there is also a spin-weighted synthesis and analysis to accompany `plan_spinsph2fourier`. There's an example for spin-weighted transforms too https://juliaapproximation.github.io/FastTransforms.jl/dev/generated/spinweighted/.

Note that connecting associated Legendre functions doesn't mix columns nor real and imaginary parts within a column, so the example above is fine (i.e. it *shouldn't* give a real-valued matrix). But to be sure, synthesizing a hermitian signal gives a real-valued output:
```julia
julia> U = [1. 2+im 2-im; 4. 0 0]
2×3 Array{Complex{Float64},2}:
 1.0+0.0im  2.0+1.0im  2.0-1.0im
 4.0+0.0im  0.0+0.0im  0.0+0.0im

julia> P = plan_spinsph2fourier(U, 0)
FastTransforms Spin-weighted spherical harmonic--Fourier plan for 2×3-element array of Complex{Float64}

julia> PS = plan_spinsph_synthesis(U, 0)
FastTransforms plan for FFTW Fourier synthesis on the sphere (spin-weighted) for 2×3-element array of Complex{Float64}

julia> F = PS*(P*U)
2×3 Array{Complex{Float64},2}:
   2.64128+0.0im   1.59861+0.0im  0.752327+0.0im
 -0.122677+0.0im  -1.16534+0.0im  -2.01163+0.0im

```
and a skew-hermitian signal synthesizes purely imaginarily:
```julia
julia> U = [0. -2-im 2-im; 0. 0 0]
2×3 Array{Complex{Float64},2}:
 0.0+0.0im  -2.0-1.0im  2.0-1.0im
 0.0+0.0im   0.0+0.0im  0.0+0.0im

julia> F = PS*(P*U)
2×3 Array{Complex{Float64},2}:
 0.0-0.488603im  0.0+1.09059im  0.0-0.601983im
 0.0-0.488603im  0.0+1.09059im  0.0-0.601983im

```

**Comment by MikaelSlevinsky** [comment]
Also, note that if using `plan_spinsph2fourier(::Type{T}, n::Int, s::Int) where T`, then the second integer is the spin, *not* the second dimension of the array. The maximum second dimension is inferred from the first integer, `2n-1`.

**Comment by MikaelSlevinsky** [comment]
The spin-weighted codepath uses orthonormal complex exponentials. As for phase, I chose what in my opinion is the simplest: positive real phase. Perhaps there are legitimate reasons to consider to changing phase conventions.

**Comment by dlfivefifty** [comment]
ah I see I misread its just cos and sin in θ but exp in φ.

**Comment by dlfivefifty** [comment]
you should define what you mean by "associated Legendre functions" since I think the version I'm using has the `(-1)^abs(m)` incorporated already

**Comment by dlfivefifty** [comment]
PS Got it working! Adaptive SHT:
```julia
julia> S = SphericalHarmonic()
SphericalHarmonic{Complex{Float64}}

julia> xyz = axes(S,1);

julia> f = p -> ((x,y,z) = p; exp(x)*cos(y*sin(z)));

julia> @time u = S * (S \ f.(xyz))
  0.010381 seconds (26.80 k allocations: 3.828 MiB)
SphericalHarmonic{Complex{Float64}} * Complex{Float64}[4.05681442931116 + 0.0im, 1.5777291816142751 + 3.19754060061646e-16im, -8.006900295635809e-17 + 0.0im, 1.5777291816142751 - 3.539535261006306e-16im, 0.3881560551355611 + 5.196884701505137e-17im, -7.035627371746071e-17 + 2.5784941810054987e-18im, -0.30926350498081934 + 0.0im, -6.82462130695514e-17 - 3.515332651034677e-18im, 0.3881560551355611 - 6.271963079558218e-17im, 0.06830566496722756 - 8.852861226980248e-17im  …  ]

julia> p = SphericalCoordinate(0.1,0.2); @test u[p] ≈ f(p)
Test Passed
```

**Comment by MikaelSlevinsky** [comment]
I think the definitions here are clear https://mikaelslevinsky.github.io/FastTransforms/transforms.html. The associated Legendre functions with integer order and degree are those polynomials from Wikipedia https://en.wikipedia.org/wiki/Associated_Legendre_polynomials, the ones in the Table of Integrals, Series, and Products S 8.81, and Ferrers' functions from DLMF https://dlmf.nist.gov/14.7#E8 (since the DLMF decides to define associated Legendre functions only for x > 1).

For m>0, I peel off the (-1)^m so that the latitudinal functions are all asymptotically positive near the North pole. And I treat the negative m spherical harmonics with the same latitudinal basis, hence the use of absolute values.

**Comment by MikaelSlevinsky** [comment]
I suppose I could remove replace associated Legendre functions with weighted Jacobi polynomials (though this would still being annoying for physicists who use the associated functions). There's usually less confusion with Jacobis

**Comment by dlfivefifty** [comment]
I see there's the "acoustics" and "quantum mechanics" SHs in https://en.wikipedia.org/wiki/Spherical_harmonics

I was using the latter with the extra `(-1)^m` while you were using the former. fine whatever

**Comment by MikaelSlevinsky** [comment]
I suppose we should support multiple phases and normalizations, either here or in the other repository.
