### ISSUE TITLE
No tests for nufft routines

### ISSUE THREAD

**Issue by gwater** [JuliaApproximation/FastTransforms.jl#132]
Tests only cover nudft routines which are not exported/acvertised in documentation. As a result nufft2 is unusable without any indication from tests.

**Comment by MikaelSlevinsky** [comment]
Not sure that's true. This test uses the direct transforms to establish a comparison
https://github.com/JuliaApproximation/FastTransforms.jl/blob/8625a440488c79e40355ab966bb805dc9650cfde/test/nuffttests.jl#L50-L52

**Comment by gwater** [comment]
It looks like `nufft2` works now and there is some minimal documentation.

To prevent `nufft2` from breaking again in the future, I nevertheless recommend some direct test coverage.
