### ISSUE TITLE
AD and FastTransforms

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [JuliaApproximation/FastTransforms.jl#133]
Great work on this package! 

As far as I can see FastTransforms (I am interested exclusively in spherical harmonics) is not usable with the current automatic differentiation implementations. In case it actually is, I am very curious to hear how. Is there some way how to make this work? I was trying out an old version which was still purely Julia as well (this should be easier for AD, right?), but I actually did not get it to run in a current Julia 1.5 installation.

**Comment by dlfivefifty** [comment]
It should be easy to add as it's a linear operator: you just apply the transform to the derivatives as well.

Which auto-diff package are you using?

**Comment by maximilian-gelbrecht** [comment]
I am using Zygote (within DiffEqFlux).

**Comment by MikaelSlevinsky** [comment]
Posting (pseudo)-code that you want to have working (with expected output) might help in this case.

**Comment by maximilian-gelbrecht** [comment]
I can't find the function definitions in the code for the individual matrix multiplications / plan types but in principle as far as I can see this: 

The matrix multiplications of the plans of 
`plan_sph2fourier, fourier2sph, plan_sph_synthesis, plan_sph_analysis`
with a vector 

With the plan called `P` and the input called `V`, I want to take the derivative of  `P*V`, so get `P*V'` 

Being a complete novice to Zygote as well, I guess this looks something like  
`@adjoint mul(P::Plan,V::Vector) = mul(P,V), x->(p*x,v*x)`

**Comment by MikaelSlevinsky** [comment]
Yeah it should be pretty straightforward. This code finds a parameter value such that the function has a unit 2-norm on the on the surface of the unit sphere:

```julia
julia> # # Automatic differentiation through spherical harmonic transforms
       # This example finds a positive value of $\lambda$ in:
       # ```math
       # f(r) = \sin(\lambda k\cdot r),
       # ```
       # for some $k,r\in\mathbb{S}^2$ such that $\int_{\mathbb{S}^2} f^2 {\rm\,d}\Omega = 1$.
       # We do this by using derivative information through:
       # ```math
       # \dfrac{\partial f}{\partial \lambda} = (k\cdot r) \cos(\lambda k\cdot r).
       # ```

       using FastTransforms, LinearAlgebra

julia> # The colatitudinal grid (mod $\pi$):
       N = 15
15

julia> θ = (0.5:N-0.5)/N
0.03333333333333333:0.06666666666666667:0.9666666666666667

julia> # The longitudinal grid (mod $\pi$):
       M = 2*N-1
29

julia> φ = (0:M-1)*2/M
0.0:0.06896551724137931:1.9310344827586208

julia> # We precompute a spherical harmonic--Fourier plan:
       P = plan_sph2fourier(Float64, N)
FastTransforms Spherical harmonic--Fourier plan for 15×29-element array of Float64

julia> # And an FFTW Fourier analysis plan on $\mathbb{S}^2$:
       PA = plan_sph_analysis(Float64, N, M)
FastTransforms plan for FFTW Fourier analysis on the sphere for 15×29-element array of Float64

julia> # Our choice of $k$ and angular parametrization of $r$:
       k = [2/7, 3/7, 6/7]
3-element Array{Float64,1}:
 0.2857142857142857
 0.42857142857142855
 0.8571428571428571

julia> r = (θ,φ) -> [sinpi(θ)*cospi(φ), sinpi(θ)*sinpi(φ), cospi(θ)]
#119 (generic function with 1 method)

julia> # Our initial guess for $\lambda$:
       λ = 1.0
1.0

julia> for _ in 1:7
           F = [sin(λ*(k⋅r(θ,φ))) for θ in θ, φ in φ]
           Fλ = [(k⋅r(θ,φ))*cos(λ*(k⋅r(θ,φ))) for θ in θ, φ in φ]
           U = P\(PA*F)
           Uλ = P\(PA*Fλ)
           global λ = λ - (norm(U)^2-1)/(2*sum(U.*Uλ))
           println("λ: $(rpad(λ, 18)) and the 2-norm: $(rpad(norm(U), 18))")
       end
λ: 0.5565017029393282 and the 2-norm: 1.8510924318185522
λ: 0.503157126283971  and the 2-norm: 1.1041845914870365
λ: 0.5010418434316173 and the 2-norm: 1.0040147091934821
λ: 0.5010383094266806 and the 2-norm: 1.0000066984258864
λ: 0.5010383094167955 and the 2-norm: 1.0000000000187363
λ: 0.5010383094167955 and the 2-norm: 1.0               
λ: 0.5010383094167955 and the 2-norm: 1.0               

julia> 
```

As you can see above, the main idea with AD is to intercept calls to the execution of the plans with the appropriate number type. This could likely look like how complex numbers are currently handled:
https://github.com/JuliaApproximation/FastTransforms.jl/blob/8625a440488c79e40355ab966bb805dc9650cfde/src/libfasttransforms.jl#L886-L908

**Comment by dlfivefifty** [comment]
The question is where should this code live.

Id argue add this support for all ` <: Plan ` and put it in Zygote.jl. A good place to start would be to find where auto-diff with FFTW.jl lives

**Comment by MikaelSlevinsky** [comment]
So these plans are instances of the `FTPlan`, *not* AbstractFFTs.jl's `Plan`. I agree, the code should live in a distinct repository that doesn't make this (or Zygote) dependent one way or the other.

**Comment by dlfivefifty** [comment]
Just make ` FtPlan <: Plan `

**Comment by maximilian-gelbrecht** [comment]
Am I missing something there or is the example not really using AD? On first glance it look more like "manual" optimisation. 

Concerning Zygote: 
FFTW is integrated into Zygote via `AbstractFFTs`, it's a dependency of Zygote and the adjoints are in Zygote's repository, could somehow FastTransforms use this as well? Anyway just copying over the adjoint from FFT and adjusting it seems to work (FastTransforms has no region field as AbstractFFT does), 

```Julia 
using FastTransforms, LinearAlgebra, Zygote

N1 = 5;
N2 = 11;

A = sphrandn(Float64, N1, N2); # convenience method
T = plan_sph2fourier(A);

Zygote.@adjoint function *(P::FastTransforms.FTPlan, xs)
   return P * xs, function(Δ)
     return (nothing, (P \ Δ))
   end
 end

Zygote.refresh()
y,back = pullback(x->T*x,A)
```
However, I am quite new to AD, so I struggle to come up with a proper test.  Is it also really P\Δ and not P*Δ?

**Comment by dlfivefifty** [comment]
Can you link the code where Zygote supports AbstractFFTs? Might be an easy fix. (all plans are linear and so AD is trivial.)

**Comment by MikaelSlevinsky** [comment]
Yeah you're right, the example code is a manual implementation of AD. Some plans may be executed in the forward direction (*) and the backward direction (\) depending on what's meant

**Comment by maximilian-gelbrecht** [comment]
> Can you link the code where Zygote supports AbstractFFTs? Might be an easy fix. (all plans are linear and so AD is trivial.)

https://github.com/FluxML/Zygote.jl/blob/master/src/lib/array.jl    line 708ff.

**Comment by dlfivefifty** [comment]
Pretty sure making ` FtPlan <: Plan ` will makes it work: 

https://github.com/FluxML/Zygote.jl/blob/956cbcf3c572c0eb09c146189bb38b1b434634ff/src/lib/array.jl#L729

can you try that and make a PR?

**Comment by maximilian-gelbrecht** [comment]
The FTPlan has no field `region`, and according to AbstractFFTs all Plans also need the subfield `pinv` for the inverse plan which is not needed here for Zygote but might lead to some errors somewhere else. 

I've been trying a small, dump example and also had an error there 

``Julia 
begin
    using Flux
    using Zygote
    using LinearAlgebra
    using FastTransforms
    using Random
end

# just ignoring any normalisation here for a moment
Zygote.@adjoint function *(P::FastTransforms.FTPlan, xs)
   return P * xs, function(Δ)
     return (nothing, (P \ Δ))
   end
 end

Zygote.@adjoint function \(P::FastTransforms.FTPlan, xs)
  return P \ xs, function(Δ)
    return (nothing, (P * Δ))
  end
end
Zygote.refresh()

N = 15
M = 2*N-1

P = plan_sph_synthesis(Float64, N, M)
PINV = plan_sph_analysis(Float64,N, M)

data = rand(Float64, N,M)

initW=(dims...)->rand(Float64,dims...) # flux is by default float32
initb=(dims...)->zeros(Float64, dims...)

# stupid example of transforming back and forth and the one linear layer just learning the identity 
nn = Chain(x->P*x, x->reshape(x,:), Dense(N*M,N*M,initW=initW,initb=initb), x->reshape(x,N,M), x->PINV*x)

pars = params(nn)
loss(x,y) = sum(abs2,nn(x) .- y)
loss(data,data) # precompile

grads = gradient(() -> loss(data, data), pars) # does not work 

# example with FFTW / DCT works 
DCT = plan_dct(data)
iDCT= plan_idct(data)

nn = Chain(x->DCT*x, x->reshape(x,:), Dense(N*M,N*M,initW=initW,initb=initb), x->reshape(x,N,M), x->iDCT*x) 
loss(x,y) = sum(abs2,nn(x) .- y)
loss(data,data) # precompile

grads = gradient(() -> loss(data, data), pars)
```
The first gradient call yields a `ERROR: LoadError: MethodError: no method matching ldiv!(::FastTransforms.FTPlan{Float64,2,20}, ::Array{Float64,2})` that is invoked by the ldiv from the adjoint (`P\Δ`) above.

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty, if I understand correctly, Zygote's reverse-mode AD is defining the adjoint of an AbstractFFTs Plan in terms of a scaled inverse. I think this is possible for most (if not all) FFTW plans, but if the adjoint definition is the linear-algebraic one, then the adjoint of `sph2fourier` is definitely *not* accessible via `fourier2sph`.

I think this could be done, but would involve some extension of the C API, essentially these drivers https://github.com/MikaelSlevinsky/FastTransforms/blob/a55eb9c62ea1faff73fee14a703871b20c005449/src/drivers.c#L823-L837 would need to be supplied with a `char TRANS` like the BLAS.

**Comment by dlfivefifty** [comment]
I think "adjoint" means "derivative" or something in Zygote...

**Comment by dlfivefifty** [comment]
i.e. all plans are `A*x`. So all plan derivates are `A*x + A* δx`...

**Comment by dlfivefifty** [comment]
So I reckon overloading `ldiv!(::FastTransforms.FTPlan{Float64,2,20}, ::Array{Float64,2})` will make the code work. Don't see where a `TRANS` comes in here

**Comment by dlfivefifty** [comment]
Sorry I think we do in fact need "adjoints of the Jacobian"

https://fluxml.ai/Zygote.jl/dev/adjoints/

so yes, @MikaelSlevinsky we need more `TRANS` support in this package

**Comment by maximilian-gelbrecht** [comment]
Again, I am by no means an expert with AD or the spherical transforms, but set aside the plans for a moment this works: 

```Julia 
begin
    using Flux
    using Zygote
    using LinearAlgebra
    using FastTransforms
    using Random
end

# let's forget about scaling/normalization for a moment, as we are transforming back and forth anyway
Zygote.@adjoint function sph2fourier(xs)
  return sph2fourier(xs), function(Δ)
    return (fourier2sph(Δ),)
  end
end

Zygote.@adjoint function fourier2sph(xs)
  return fourier2sph(xs), function(Δ)
    return (sph2fourier(Δ),)
  end
end
Zygote.refresh()

N = 15
M = 2*N-1
data = sphrand(Float64,N,M)

# stupid example of transforming back and forth and the one linear function just learning the identity, really just y = m*x + b with two parameters
m = Chain(x->sph2fourier(x),x->a[1].*x.+b[1],  x->fourier2sph(x))

# arrays are required by flux for the parameters
a = [Float64(2.)]
b = [Float64(.1)]
pars = params(a,b)
loss(x,y) = sum(abs2,m(x) .- y)
loss(data,data) # precompile

for i=1:3000
    Flux.train!(loss, pars, [(data,data)],ADAMW())
    println(i,"- loss=",loss(data,data))
end
# result loss = 1e-9, a~1, b~0
```

* so, is this really the correct way? 
* what's with any normalization/scaling if not transforming back and forth
* for plans there's the `plan_fourier2sph` missing, so this wouldn't work there.

**Comment by MikaelSlevinsky** [comment]
Fourier2sph uses plan_sph2fourier and gets executed by "\" (backslash).

I think adjoints are different than inverses. Since FFTs are Vandermonde matrices at special point sets that ensure they are unitary (up to diagonal scaling), the adjoints can be implemented by using FFTW's backslash and undoing the scaling to go from inverse to adjoint.

I don't know nearly enough about Zygote to be helpful, but I wonder if (and why) they have a preference to reverse mode over forward mode AD. (Maybe this question is heretical in the world of AD?)

**Comment by maximilian-gelbrecht** [comment]
So for spherical transforms this is different than for Fourier transform plans? Yeah, I guess I will try do a bit more reading there (but where exactly I don't know yet). 

The zygote code also states that
# the adjoint jacobian of an FFT with respect to its input is the reverse FFT of the
# gradient of its inputs, but with different normalization factor
and while this makes sense to me intuitively, I don't know how to get there mathematically.

**Comment by MikaelSlevinsky** [comment]
Spherical harmonic transforms could, in principle, be unitary. But I think that would mean evaluation at Gauss(-Legendre) nodes on the sphere rather than equispaced in angle (aka equispaced cylindrical projection).

In this repository, the SHT is split into a (non-unitary) coefficient conversion to bivariate Fourier series and the unitary-up-to-diagonal-scaling FFTW synthesis/analysis. The main benefit of this approach is to route synthesis and analysis through Fourier series, which can then be done much more easily with non uniform FFTs at a point set of one's choosing.

**Comment by maximilian-gelbrecht** [comment]
Thank you for all your input concerning this. 

Reverse AD is more useful as it scales much better with the amount of different derivatives you want to take, i.e. parameters to optimise. I also have a model in mind with many parameters, so this would be advantageous. 
Regarding the adjoint/pullback: In a normal matrix multiplication: `C=A*B` where `A = const`, the adjoint would be `x -> A^T*x`. When FTs are unitary, then it makes sense that their adjoint / pullback is defined via the inverse transform. I don't know what the transpose of the spherical harmonics transform plan is. 

On the other side, Forward AD is conceptually much simpler, however also not super straightforward to implement with ForwardDiff.jl. It really does not seem to be the normal use case of the ForwardDiff.jl to define derivates of calls to binaries, it is Julia code only with some exceptions that are only very sparsely documented unfortunately. One needs implement the derivative rule apparently (easy) and then also the functions defined for Dual numbers (very sparsely documented how to implement that). There is ChainRules.jl for defining these rules as well, but it does not seem to work together with ForwardDiff (yet?). 

Your library started in pure Julia, right? Wonder if it actually be simpler to make that old code running again for AD.

**Comment by dlfivefifty** [comment]
I think it'd be simpler to just wait for Mikael to implement transposes... should only take him a few hours 😜

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty, you're right: it warmed up above -40 today (with windchill) so the daycare re-opened and I didn't have any lectures.

Ok, @maximilian-gelbrecht, on the master branch (`] add FastTransforms#master`), you can get a feel for what I'm proposing. You'll have to set the environment variable `FT_BUILD_FROM_SOURCE=true` and rebuild the repository locally.

I have a dream that the Zygote adjoint macro should be implemented as simply as this:
```julia
@adjoint function *(P::FastTransforms.FTPlan, xs)
  return P * xs, function(Δ)
    return (nothing, P'Δ)
  end
end
@adjoint function \(P::FastTransforms.FTPlan, xs)
  return P \ xs, function(Δ)
    return (nothing, P'\Δ)
  end
end
```
All it does it call for an implementation of the adjoint. If it doesn't exist, it will throw an error gracefully.

On master, I've got adjoints working for `sph2fourier`, `fourier2sph`, `plan_sph_synthesis` and `plan_sph_analysis` (and also the vector field routines).

Here is code that checks that the adjoints are implemented correctly:
```julia
# ENV["FT_BUILD_FROM_SOURCE"] = "true"
# ] build FastTransforms
# You need GCC/clang to compile the C lib

using FastTransforms, Test

n = 10
m = 2n-1

p = plan_sph2fourier(Float64, n) # A man, a plan, a canal: Panama!
P = zeros(n*m, n*m); # Kronecker'ed linear operator
for j in 1:m
    for i in 1:n
        e = zeros(n, m) # col'th column of the identity
        e[i,j] = 1.0
        col = i+(j-1)*n
        P[:, col] .= vec(p*e) # col'th column of the Kronecker'ed linear operator
    end
end

Q = zeros(n*m, n*m); # Same thing now, but with the adjoint
for j in 1:m
    for i in 1:n
        e = zeros(n, m)
        e[i,j] = 1.0
        col = i+(j-1)*n
        Q[:, col] .= vec(p'e)
    end
end

@test P' ≈ Q
```

The new version of `AdjointFTPlan` is great because it gives one the freedom to use the original `FTPlan` or to define a bespoke adjoint plan, while still preserving the "truth" `p'' === p`. https://github.com/JuliaApproximation/FastTransforms.jl/blob/c3da771761ddfb061eb49c0c12c2b5d7bebd5a65/src/libfasttransforms.jl#L269-L278

If you're happy with this approach, please let me know. I'm going to see if I can implement a few more adjoints this week before tagging new minor releases to the C code and the Julia wrapper.

**Comment by maximilian-gelbrecht** [comment]
This is awesome. I can't thank you enough for your quick work on that. 

Your test works for me as well and my dumb test with Zygote from above (slightly adjusted) as well. One question though, it is obvious for me how this works with all the plans like `plan_sph2fourier`, `plan_sph_synthesis` and `plan_sph_analysis`. How does it work for `fourier2sph`though where there's no plan?

**Comment by MikaelSlevinsky** [comment]
Cheers! I'm just waiting for GitHub Actions to recognize a new binary tag for the doc builds to pass, then I'll tag a minor release so we can go back to precompiled binaries.

For the use of the adjoint macro for `fourier2sph`, I'd say it's like how it's done for `fft`. Probably something like this would work
```julia
@adjoint function fourier2sph(xs)
  return FastTransforms.fourier2sph(xs), function(Δ)
    return (FastTransforms.plan_sph2fourier(Δ)'\Δ, )
  end
end
```
`fourier2sph` is really just a cosmetic convenience function -- I would recommend using the plans whenever possible.

**Comment by MikaelSlevinsky** [comment]
P.S. I posted this issue https://github.com/FluxML/Zygote.jl/issues/899 regarding the generic adjoints for `AbstractFFTs.Plan`.

**Comment by maximilian-gelbrecht** [comment]
Oh, sorry, I just got a bit confused, you are right the `ldiv` from the sph2fourier is doing exactly that. 
And, yes, with FFTW there are also some things that don't work there, the `region` subfield that is used there doesn't exist for all FFTW's plans either, especially not for the actual FFT, I already posted an issue there as well https://github.com/JuliaMath/FFTW.jl/issues/182
