### ISSUE TITLE
"undefined symbol: cblas_dtrmm64_" during matrix division

### ISSUE THREAD

**Issue by meew0** [JuliaApproximation/FastTransforms.jl#146]
I am trying to compute a very simple spherical harmonics transform:

```julia
using FastTransforms

F = randn(5, 9) .+ 5
P = plan_sph2fourier(F)
PA = plan_sph_analysis(F)
V = PA * F

println("foo")
result = P \ V
println(result)
```

However, this results in the following error in the division step:

```
$ julia sph.jl
foo
julia: symbol lookup error: /home/<username>/.julia/artifacts/603bf763f4eb68f8445d34a461cea3c8156cae18/lib/libfasttransforms.so: undefined symbol: cblas_dtrmm64_
```

This happens both when using precompiled binaries and when compiling from source using `FT_BUILD_FROM_SOURCE=true`. I am using Julia 1.6.2 on Arch Linux (all packages updated), and have replicated this problem on two different machines with this setup. The problem persists when I completely remove `~/.julia` and reinstall only FastTransforms.

**Comment by MikaelSlevinsky** [comment]
Hey, so that specific symbol is only used to match Julia's renaming of 64-bit openBLAS symbols, see https://github.com/JuliaPackaging/Yggdrasil/blob/5d5f68d5115115e06aa2b6e0e6a036a2f44c6b66/O/OpenBLAS/common.jl#L59-#L65 and https://github.com/JuliaPackaging/Yggdrasil/blob/5d5f68d5115115e06aa2b6e0e6a036a2f44c6b66/F/FastTransforms/build_tarballs.jl#L28-#L38. The symbol matching appears to be a little bit off for you. That's one issue.

However, the problem should not exist if you build from source because you would be linking to a different openBLAS lib (not a Julia-provided one). Looking at the build script, there is no renaming of symbols https://github.com/JuliaApproximation/FastTransforms.jl/blob/master/deps/build.jl. Building from source might require trivially modifying a file and resaving to trigger recompilation.

**Comment by MikaelSlevinsky** [comment]
`versioninfo()` is always helpful.

**Comment by meew0** [comment]
Okay, I tried it once more, now both first deleting my `~/.julia` directory **and** building FastTransforms from source. There is still a symbol lookup error, however the symbol is different, without the `64_` (what I assume is the "unmapped" one):

```
julia> result = P \ V
julia: symbol lookup error: /home/<username>/.julia/packages/FastTransforms/47F6t/deps/libfasttransforms.so: undefined symbol: cblas_dtrmm
```

My `versioninfo()`:

```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4* (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 5900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
```

And a full log of what I did — including the `build.log`, in case it is helpful: https://gist.github.com/meew0/7c050b31864af6b5e9d15bf649f8be4b

**Comment by MikaelSlevinsky** [comment]
It looks like the built library is not finding the OpenBLAS library dependency. Do you know if it's installed? Kind of surprised it's compiling.

**Comment by meew0** [comment]
Yes, I have installed the Arch [openblas](https://archlinux.org/packages/community/x86_64/openblas/) package, and the library is present at `/usr/lib/libopenblas.so`.

**Comment by MikaelSlevinsky** [comment]
Hmm, what's strange is that this is happening for both the precompiled binaries and the build from source.

On macOS, I can use `otool` to check the paths for the libraries linked (On macOS, there's an option to use the Accelerate BLAS instead of OpenBLAS, but haven't had an issue). Can you see if your compilation is finding the right paths to the libraries for your system?

```
mikael@scima-mh464-20 FastTransforms % otool -L libfasttransforms.dylib
libfasttransforms.dylib:
	libfasttransforms.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/libomp/lib/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	/usr/local/opt/mpfr/lib/libmpfr.6.dylib (compatibility version 8.0.0, current version 8.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/fftw/lib/libfftw3.3.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/local/opt/fftw/lib/libfftw3_threads.3.dylib (compatibility version 10.0.0, current version 10.9.0)
```

**Comment by meew0** [comment]
Using `ldd` on the `libfasttransforms.so` compiled from source, given the path from the error message:

```
$ ldd ~/.julia/packages/FastTransforms/47F6t/deps/libfasttransforms.so
        linux-vdso.so.1 (0x00007ffd137eb000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f7e3f42d000)
        libmpfr.so.6 => /usr/lib/libmpfr.so.6 (0x00007f7e3f180000)
        libopenblas.so.3 => /usr/lib/libopenblas.so.3 (0x00007f7e3de5a000)
        libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x00007f7e3dc15000)
        libfftw3_threads.so.3 => /usr/lib/libfftw3_threads.so.3 (0x00007f7e3dc0c000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f7e3dbc8000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7e3dba5000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f7e3d9d9000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7e3f6cd000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f7e3d939000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7e3d932000)
```

However, `ldd -u` shows it as an "unused dependency":

```
$ ldd -u ~/.julia/packages/FastTransforms/47F6t/deps/libfasttransforms.so
Unused direct dependencies:
        /usr/lib/libopenblas.so.3
        /usr/lib/libpthread.so.0
```

There is also a `libfasttransforms.so` in a folder in `~/.julia/artifacts` (not quite sure if this one is also compiled from source), where it shows only libopenblas as "not found":

```
$ ldd ~/.julia/artifacts/603bf763f4eb68f8445d34a461cea3c8156cae18/lib/libfasttransforms.so  
        linux-vdso.so.1 (0x00007ffe0c1f8000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fc0c15cd000)
        libmpfr.so.6 => /usr/lib/libmpfr.so.6 (0x00007fc0c1320000)
        libopenblas64_.so => not found
        libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x00007fc0c10db000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fc0c1097000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc0c1076000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fc0c0ea8000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc0c1a9d000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007fc0c0e08000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fc0c0e01000)
$ ldd -u ~/.julia/artifacts/603bf763f4eb68f8445d34a461cea3c8156cae18/lib/libfasttransforms.so 
Unused direct dependencies:
        libopenblas64_.so
        /usr/lib/libpthread.so.0
```

**Comment by MikaelSlevinsky** [comment]
Hi @meew0, it's possible this issue has disappeared with new binaries (v.0.13.3) and with the new Julia version 1.7 requirement. Would you be able to confirm?

**Comment by meew0** [comment]
Installing FastTransforms with precompiled binaries fails during the package precompilation step for me now, it does not manage to find OpenBLAS at all by default:

```
julia> import FastTransforms
[ Info: Precompiling FastTransforms [057dd010-8810-581a-b7be-e3fc3b93f78c]
ERROR: LoadError: InitError: could not load library "/home/miras/.julia/artifacts/b6cc0f266db906497307ffc11f757445c3189108/lib/libfasttransforms.so"
libopenblas64_.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JLLWrappers/RYztT/src/products/library_generators.jl:54 [inlined]
 [2] __init__()
   @ FastTransforms_jll ~/.julia/packages/FastTransforms_jll/JKenj/src/wrappers/x86_64-linux-gnu.jl:12
 [3] top-level scope
   @ ~/.julia/packages/FastTransforms/hPTVh/src/libfasttransforms.jl:10
 [4] include(x::String)
   @ FastTransforms ~/.julia/packages/FastTransforms/hPTVh/src/FastTransforms.jl:1
 [5] top-level scope
   @ ~/.julia/packages/FastTransforms/hPTVh/src/FastTransforms.jl:53
 [6] top-level scope (repeats 2 times)
   @ none:1
during initialization of module FastTransforms_jll
in expression starting at /home/miras/.julia/packages/FastTransforms/hPTVh/src/libfasttransforms.jl:2
in expression starting at /home/miras/.julia/packages/FastTransforms/hPTVh/src/FastTransforms.jl:1
ERROR: Failed to precompile FastTransforms [057dd010-8810-581a-b7be-e3fc3b93f78c] to /home/miras/.julia/compiled/v1.7/FastTransforms/jl_o3xmQe.
```

If I manually create a symlink `/usr/lib/libopenblas64_.so -> /usr/lib/libopenblas.so`, the installation works but the same error as before occurs:

```
julia: symbol lookup error: /home/miras/.julia/artifacts/b6cc0f266db906497307ffc11f757445c3189108/lib/libfasttransforms.so: undefined symbol: cblas_dtrmm64_
```

Installing using `FT_BUILD_FROM_SOURCE=true` works even without a manual symlink but using the library does not, with the same "slightly different" error:

```
julia: symbol lookup error: /home/miras/.julia/packages/FastTransforms/hPTVh/deps/libfasttransforms.so: undefined symbol: cblas_dtrmm
```

I haven't changed anything else relevant about my system, as far as I can tell. `ldd` and `ldd -u` have essentially the same output as before. My `versioninfo` now:

```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908* (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 5900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, znver3)
```

**Comment by meew0** [comment]
> How did you install Julia exactly?

`pacman -S julia` :)

**Comment by giordano** [comment]
Don't use use that package, it's broken.  Use [`aur:julia-bin`](https://aur.archlinux.org/packages/julia-bin/) instead

**Comment by meew0** [comment]
Ah, good to know... Everything appears to work perfectly using that package. I'll close this issue then, as the problems I ran into have thus been solved
