### ISSUE TITLE
nufft2

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaApproximation/FastTransforms.jl#158]
I am having trouble understanding what nufft2 does. Is `x` not the list of spatial source coordinates of the transform?
But the following code seems to not agree with this assumption:
```julia
julia> q = ones(ComplexF64,8);

julia> x= collect(0.0:7.0);

julia> p1 = plan_nufft2(x, eps());

julia> p1*q
8-element Vector{ComplexF64}:
 8.0 + 0.0im
 8.0 + 0.0im
 8.0 + 0.0im
 8.0 + 0.0im
 8.0 + 0.0im
 8.0 + 0.0im
 8.0 + 0.0im
 8.0 + 0.0im
```
I expected a delta peak at the zero frequency but the result is a uniform, frequency independent constant distribution (==8.0).
`nufft2` yield the same result as this planned version.
Bug or a misunderstanding?

**Comment by MikaelSlevinsky** [comment]
I think the spatial coordinates ought to be between 0 and 1? You can check the docs for specific formulae and tests for sample usage.

**Comment by RainerHeintzmann** [comment]
I see. Thanks a lot! Indeed, this seems to do the trick. Just a bit unexpected, that the real-space index over the data is (0..N-1)/N whereas the Fourier-space index is 0...N-1. Maybe worth putting into the help file, which is also very hard to read, as it seems written in LaTeX and does not show the function signature?

**Comment by RainerHeintzmann** [comment]
Hmmm. But looking at this example:
```julia
julia> q = ones(ComplexF64,8);

julia> w = [0.0,0.1,0.2,0.3,0.5,0.6,0.8,0.9];

julia> nufft2(q,w,eps())
8-element Vector{ComplexF64}:
                     8.0 + 0.0im
     -1.1180339887498953 - 1.5388417685876248im
      0.5000000000000028 - 1.5388417685876257im
       1.118033988749897 - 0.3632712640026772im
 -2.4265920544095115e-17 + 0.0im
      0.4999999999999996 - 0.3632712640026794im
       0.500000000000005 + 1.538841768587626im
      -1.118033988749896 + 1.5388417685876274im
```
does not look great. I would have expected a result very close to a delta at zero frequency, if not identical, but the deviations are rather strong.
I was trying to use `nufft2()` to implement a chirped stretching of an image and this fails massively and it looks to me a bit like `nufft2()` is still yielding a non-uniform sampling in Fourier-space rather than in real space. Looking at the code of `plan_nufft2()`it seems also largely identical to `plan_nufft1()` except for the scaling. But maybe I am missing something here?

**Comment by RainerHeintzmann** [comment]
... looking at `plan_nufft3` seems to point a way how to fix this?
Line 40: `  t = AssignClosestEquispacedFFTpoint(x)` may be where it starts going wrong, juding from the name?

**Comment by RainerHeintzmann** [comment]
Sorry. You are right. It computes exactly what it is supposed to looking at the equations in the doc.
https://juliaapproximation.github.io/FastTransforms.jl/stable/#Introduction-1
Its just more difficult that I thought to use nufft for real space non-uniform stretching.
