### ISSUE TITLE
Move generic FFT into its own package?

### ISSUE THREAD

**Issue by cgeoga** [JuliaApproximation/FastTransforms.jl#172]
The generic Bluestein-based FFT in this package is great, and I use it often. But this package has a lot of heavy dependencies that I don't really want to add to my projects, and the FFT is very often the only functionality I use from it. Would it make sense to potentially move/mirror it to its own package, or potentially even put it in `AbstractFFTs.jl`? As it stands, to avoid cluttering the dependency tree of my projects I even sometimes just copy that single file (with proper attribution, to be clear). 

If the idea is not objectionable but you don't feel like doing it, would you object to somebody else (for example me) copying it and creating, say, `Bluestein.jl`?

I see an existing issue (#86) asking something similar, where the proposed solution is that `FourierTransforms.jl` will provide nice multidimensional transforms. But that package isn't registered and hasn't seen a commit since 2019. While eventually that seems like a very natural home for such functionality, maybe something that is registered and offers something lighter in the mean time would make sense.

**Comment by dlfivefifty** [comment]
I think we'd definitely support this

**Comment by cgeoga** [comment]
Hey, excellent. What makes the most sense as far as execution? Would you like me (or some other volunteer that isn't one of the main devs here) to make the repo and set up tests and stuff and then transfer it (?) to JuliaApproximation or something? To be honest I don't have a great understanding of the `fftBigFloat.jl` file and so it would be a pretty minimal copy-paste job if I did it. 

Maybe @mfherbst has an opinion as well?

**Comment by dlfivefifty** [comment]
Yes exactly. I don't think me or @MikaelSlevinsky have time to do this ourselves so just needs someone to take the initiative.

I don't have strong opinions on where it ends up.

**Comment by milankl** [comment]
Just saying that there's also interest on our side, as we are looking for a generic FFT for use in [SpeedyWeather.jl](https://github.com/milankl/SpeedyWeather.jl). Very happy to contribute, but I currently don't have an overview of what's needed where. If someone could come up with a plan what's needed, happy to execute some of the steps in it.

**Comment by dlfivefifty** [comment]
It just takes someone to take the lead, which would include deciding "what's needed where". @mfherbst gave a reasonsable proposal.

**Comment by daanhb** [comment]
I'd be a happy user of a separate package for generic FFT's

**Comment by cgeoga** [comment]
Thanks! Sorry to have been radio silent on this for so long. I appreciate the initiative you took for it. I have a couple comments/questions, but I'll open them as issues on that page.

**Comment by daanhb** [comment]
The [GenericFFT.jl](https://github.com/JuliaApproximation/GenericFFT.jl) package has been registered at version 0.1.0. There were some tweaks to dependencies, but the transform itself is the exact same code as it was here in FastTransforms so it should be functionally equivalent for everyone who used FastTransforms for that purpose.

FastTransforms extended DSP.conv for general AbstractFloat types in terms of the FFT. That part was removed from GenericFFT, in order not to depend on DSP. An issue was filed to fix this [upstream](https://github.com/JuliaDSP/DSP.jl/pull/477) so hopefully in the future 'conv' will just work.

**Comment by daanhb** [comment]
Thanks everyone here for the quick responses!
