### ISSUE TITLE
Remove DSP dependency

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/FastTransforms.jl#176]
Removing DSP from FastTransforms reduces the load time from 3.7 s to 2.8 s for me, a 25% savings. @dlfivefifty, is there any downstream reason not to remove DSP?

**Comment by dlfivefifty** [comment]
I thought we need it for ` conv ` ?

**Comment by MikaelSlevinsky** [comment]
If https://github.com/JuliaDSP/DSP.jl/pull/477 gets merged, then generic convolution will have nothing to do with this repository.

**Comment by MikaelSlevinsky** [comment]
This issue will be closed today with a *patch* release since https://github.com/JuliaDSP/DSP.jl/pull/477 has been merged, FastTransforms re-exports GenericFFT, and ToeplitzMatrices (a FastTransforms dependency) has been tagged (https://github.com/JuliaMatrices/ToeplitzMatrices.jl/commit/c6f3a2487448e642e18db10b7e39090c432b3300) to ensure the newest DSP patch or greater, [0.7.7, 0.8.0), is loaded.

**Comment by MikaelSlevinsky** [comment]
That is, no loss of features (no breaking changes) for the user.
