### ISSUE TITLE
Should multiplication of `FTPlan` take `StridedArray`s as arguments instead of `Array`s?

### ISSUE THREAD

**Issue by jishnub** [JuliaApproximation/FastTransforms.jl#178]
https://github.com/JuliaApproximation/FastTransforms.jl/blob/8a82d79f7065fd1ae7363384248e6570216a93b2/src/libfasttransforms.jl#L1080-L1085

Should these act on `StridedArrays`s instead of `Array`s? In that case, views would work as well. If the stride along the first axis must be `1`, we may add a test for this.

Also, is `deepcopy` needed here? `copy` should be identical for an array of structs. Or is this required to deal with `BigFloat` arrays?

**Comment by MikaelSlevinsky** [comment]
Yeah I think strided arrays should work. Right now, unit stride assertion would be necessary but the 1-D plans could all be made to work with more general stride in the first axis. (The multidimensional plans rely on some hardware-specific instructions for speed up so a non-unit stride would throw all that away.)
