### ISSUE TITLE
What algorithm does cheb2leg() use?

### ISSUE THREAD

**Issue by kuandeng** [JuliaApproximation/FastTransforms.jl#187]
Hi！I am looking for the implementation of the cheb2leg algorithm mentioned in paper “FAST POLYNOMIAL TRANSFORMS BASED ON
TOEPLITZ AND HANKEL MATRICES", but it seems that the implementation in this package is different from the algorithm in that article.

 I wonder which paper does the cheb2leg() implementation in this package come from? And does the cheb2leg algorithm in paper “FAST POLYNOMIAL TRANSFORMS BASED ON TOEPLITZ AND HANKEL MATRICES"have a julia or c implementation?

**Comment by MikaelSlevinsky** [comment]
It's in the transforms chapter in the second reference in the readme

S. Olver, R. M. Slevinsky, and A. Townsend. Fast algorithms using orthogonal polynomials, Acta Numerica, 29:573—699, 2020.

**Comment by kuandeng** [comment]
Thank you for your anwser!

**Comment by kuandeng** [comment]
> It's in the transforms chapter in the second reference in the readme
> 
> S. Olver, R. M. Slevinsky, and A. Townsend. Fast algorithms using orthogonal polynomials, Acta Numerica, 29:573—699, 2020.

Thank you for your anwser!
