### ISSUE TITLE
Chebyshev transforms do not work with the FFTW v1.6.

### ISSUE THREAD

**Issue by JiyangHe** [JuliaApproximation/FastTransforms.jl#195]
I update FFTW to v1.6. Then the Chebyshev transforms do not work. The error is following:

julia> using FastTransforms

julia> begin
                            n=20
                            p_1 = chebyshevpoints(Float64, n, Val(1))
                            f = exp.(p_1)
                            f̌ = chebyshevtransform(f, Val(1))
                            end
ERROR: MethodError: no method matching (FastTransforms.ChebyshevTransformPlan{Float64, 1, (5,)})(::FFTW.r2rFFTWPlan{Float64, Tuple{Int32}, false, 1, Tuple{Int64}})
Closest candidates are:
  (FastTransforms.ChebyshevTransformPlan{T, kind, K})(::FFTW.r2rFFTWPlan{T, K, inplace, N, R}) where {T, kind, K, inplace, N, R} at ~/.julia/packages/FastTransforms/bNP7D/src/chebyshevtransform.jl:18
Stacktrace:
 [1] #plan_chebyshevtransform#174
   @ ~/.julia/packages/FastTransforms/bNP7D/src/chebyshevtransform.jl:41 [inlined]
 [2] plan_chebyshevtransform
   @ ~/.julia/packages/FastTransforms/bNP7D/src/chebyshevtransform.jl:37 [inlined]
 [3] #chebyshevtransform#179
   @ ~/.julia/packages/FastTransforms/bNP7D/src/chebyshevtransform.jl:218 [inlined]
 [4] chebyshevtransform(x::Vector{Float64}, dims::Val{1})
   @ FastTransforms ~/.julia/packages/FastTransforms/bNP7D/src/chebyshevtransform.jl:218
 [5] top-level scope
   @ REPL[2]:5

**Comment by TSGut** [comment]
I believe this is being addressed here: https://github.com/JuliaApproximation/FastTransforms.jl/pull/193

**Comment by JiyangHe** [comment]
Ok. I didn't see that. Thank you. I close this issue.
