### ISSUE TITLE
Reduction in accuracy in `cheb2leg ∘ leg2cheb` on v0.15

### ISSUE THREAD

**Issue by jishnub** [JuliaApproximation/FastTransforms.jl#201]
On v0.15, there's a slight reduction in accuracy:
```julia
julia> x = FastTransforms.chebyshevpoints(4096);

julia> f = x -> cospi(1000x);

julia> y = f.(x);

julia> v = FastTransforms.cheb2leg(FastTransforms.chebyshevtransform(y));

julia> norm(v - FastTransforms.cheb2leg(FastTransforms.leg2cheb(v)), Inf)
1.1079137607339362e-11

julia> norm(v - FastTransforms.cheb2leg(FastTransforms.leg2cheb(v)))/norm(v)
9.470824355706295e-13
```
vs on v0.14:
```julia
julia> norm(v - FastTransforms.cheb2leg(FastTransforms.leg2cheb(v)), Inf)
3.552713678800501e-15

julia> norm(v - FastTransforms.cheb2leg(FastTransforms.leg2cheb(v)))/norm(v)
3.181223251647899e-16
```
This isn't terrible, but I wonder if this may be improved?

**Comment by MikaelSlevinsky** [comment]
Yes, v0.15 was tagged too quickly.

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty, the errors in the Toeplitz-dot-Hankel method are so big that they're practically computing different things.

I propose that, to fix all the issues that arose in the v0.15 tag (thanks @jishnub), we revert the part that overrides the default `cheb2leg` and either: 1. add a keyword `method=:default` or `:TdotH` or 2. call it `th_cheb2leg` for example.

**Comment by dlfivefifty** [comment]
Oh I just need to re-add a diagonal rescaling, should be easy.

**Comment by dlfivefifty** [comment]
This is now fixed on master:
```julia
julia> norm(v - cheb2leg(leg2cheb(v)), Inf)
7.72715225139109e-14

julia> norm(v - cheb2leg(leg2cheb(v)))/norm(v)
6.291080360808277e-15
```
