### ISSUE TITLE
Write test for Normalization in `cheb2leg` and `leg2cheb`

### ISSUE THREAD

**Issue by jishnub** [JuliaApproximation/FastTransforms.jl#203]
This used to work on v0.14
```julia
julia> cheb2leg([0.0, 1.0], normcheb=true)
2-element Vector{Float64}:
 0.0
 0.7978845608028654
```
but errors on v0.15
```julia
julia> cheb2leg([0.0, 1.0], normcheb=true)
ERROR: MethodError: no method matching th_cheb2leg(::Vector{Float64}; normcheb::Bool)

Closest candidates are:
  th_cheb2leg(::Any, ::Any...) got unsupported keyword argument "normcheb"
   @ FastTransforms ~/Dropbox/JuliaPackages/FastTransforms.jl/src/toeplitzhankel.jl:282

Stacktrace:
 [1] cheb2leg(::Vector{Float64}; z::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:normcheb,), Tuple{Bool}}})
   @ FastTransforms ~/Dropbox/JuliaPackages/FastTransforms.jl/src/FastTransforms.jl:129
 [2] top-level scope
   @ REPL[29]:1
```
It would be good to get this working again

**Comment by dlfivefifty** [comment]
Ah didn't know about that keyword. You can use `FastTransforms.lib_cheb2leg` to use the old version for now. 

Note we the lib version's plan is expensive which is why we now default to `th_cheb2leg`, which has a better complexity plan, though applying the plan is slower so `plan_cheb2leg` currently defaults to the old version.

**Comment by dlfivefifty** [comment]
This has been fixed by reverting to lib_cheb2leg (though back to the restrictions of small dimension). 

I'm leaving this open as the tests should have picked this up.

**Comment by dlfivefifty** [comment]
Actually I just did it based on your example.

**Comment by MikaelSlevinsky** [comment]
Yes, apologies, there should have been tests for the normalization keywords.
