### ISSUE TITLE
cheb2leg(Float64[]) segfaults

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastTransforms.jl#31]

**Comment by MikaelSlevinsky** [comment]
This should be a quick 'isempty' fix.

Cheers,

Mikael

**Comment by MikaelSlevinsky** [comment]
This has a very quick fix at the `*` level:
```julia
function *(P::HierarchicalPlan, x::AbstractVector)
    isempty(x) && (return zero(x))
    A_mul_B!(zero(x), P, x)
end
```
but the question is how much of the `A_mul_B!` API is or should be exposed to the user. If this repository is meant to be mainly exporting `A_mul_B!`-like routines, then the `*` level is too shallow to check `isempty`. (I think Base delegates most of the error checking to LAPACK except for `_generic_matmatmul!`, which is the computational level.)

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty

**Comment by dlfivefifty** [comment]
We definitely want `A_mul_B!` overrides in this package: for time-stepping the inplace variants are crucial for efficient code. 

Though Julia v0.7 completely revamps this to `mul!`, and so there is limited utility on working on `A_mul_B!` right now.
