### ISSUE TITLE
Should the default interface be `transform!` and `itransform!`?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/FastTransforms.jl#52]
This would mirror the current `ApproxFun` transforms interface, and could help avoiding issues with converting `At_mul_B!(Y,A,X)` overrides to `mul!(Y,A',X)`. (I could be wrong, but it's not clear to me that the authors were aware of how this change in Base could affect packages that use recursive linear algebra data structures.) @dlfivefifty, thoughts?

**Comment by MikaelSlevinsky** [comment]
Is it not true that in the new paradigm, if `A` is conceptually equal to [A<sub>11</sub> A<sub>12</sub>; A<sub>21</sub> A<sub>22</sub>], then `mul!(y, A', x)` would want to create four more light types each representing the adjoint of the subblock?

I think `P*x` being in- or out-of-place is a question of convention. Do any transforms in this package function like this? (The FastTransforms C library does, because I think it's more efficient for the C plans to have their own personal aligned workspace to copy into and out of. But then it's a C-to-Julia wrapping issue.)

**Comment by dlfivefifty** [comment]
No that's not true:`A' isa Adjoint{eltype(A), typeof(A)}`. 

I don't like `P*x` being in-place because it abuses the notion of multiplication. Note it's easy to make both in-place and out-of-place work:
```julia
*(T::MyInplaceTransform, x) = lmul!(T, copy(x))
lmul!(T::MyOutofplaceTransform, x) = (x .= T*x)
```
