### ISSUE TITLE
speed regression on Julia 1.1 ?

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaApproximation/FastTransforms.jl#69]
running the readme examples 

Julia 1.1:
```julia 
using FastTransforms

F = sphrandn(Float64, 1024, 1024);

@time G = sph2fourier(F; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:05
 61.230271 seconds (598.27 M allocations: 10.007 GiB, 10.16% gc time)

@time H = fourier2sph(G; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:05
 64.233187 seconds (593.01 M allocations: 9.955 GiB, 10.55% gc time)
```

Julia 1.0.3:
```julia
F = sphrandn(Float64, 1024, 1024);

 @time  G = sph2fourier(F; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:04
 45.251658 seconds (436.73 M allocations: 7.941 GiB, 7.81% gc time)

@time H = fourier2sph(G; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:03
 49.485671 seconds (627.87 M allocations: 10.231 GiB, 11.12% gc time)
```

**Comment by MikaelSlevinsky** [comment]
When I first wrote the code (Julia v0.6 I think), the precomputation was 4 seconds and the execution was 0.6 seconds for the readme code. Indeed, there is a considerable performance regression that I haven’t kept up with.

Longer term, I have switched transform development to the C library of the same name. In C, I have finer control over SIMD vectorization and shared memory parallelization. Eventually, the Julia package will not be more than a light wrapper and thereby less susceptible to changes in the core Julia code that have unforeseen consequences elsewhere.

Cheers,

Mikael

On May 31, 2019, at 6:45 PM, Ashton Bradley <notifications@github.com<mailto:notifications@github.com>> wrote:


running the readme examples

Julia 1.1:

using FastTransforms

F = sphrandn(Float64, 1024, 1024);

@time G = sph2fourier(F; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:05
 61.230271 seconds (598.27 M allocations: 10.007 GiB, 10.16% gc time)

@time H = fourier2sph(G; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:05
 64.233187 seconds (593.01 M allocations: 9.955 GiB, 10.55% gc time)

Julia 1.0.3:

F = sphrandn(Float64, 1024, 1024);

 @time  G = sph2fourier(F; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:04
 45.251658 seconds (436.73 M allocations: 7.941 GiB, 7.81% gc time)

@time H = fourier2sph(G; sketch = :none);
Pre-computing...100%|███████████████████████████████████████████| Time: 0:00:03
 49.485671 seconds (627.87 M allocations: 10.231 GiB, 11.12% gc time)

**Comment by AshtonSBradley** [comment]
ok, thanks for the info - for now should I move to calling the C library from julia using `ccall.jl`?

**Comment by MikaelSlevinsky** [comment]
If you checkout the branch ‘feat-libfasttransforms’, then the file ‘libfasttransforms.jl’ is a start for you. Eventually, that code will evolve into the standard way.

Cheers,

Mikael

On May 31, 2019, at 9:32 PM, Ashton Bradley <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, thanks for the info - for now should I move to calling the C library from julia using ccall.jl?
