### ISSUE TITLE
Multidimensional generic FFTs, perhaps in a separate package?

### ISSUE THREAD

**Issue by mfherbst** [JuliaApproximation/FastTransforms.jl#86]
I would be interested to see the generic Fourier transforms implemented in this package to be extended to the multi-dimensional case. There's been quite some interest in generic FFTs in the community, see e.g. https://github.com/JuliaMath/AbstractFFTs.jl/issues/34 and https://github.com/JuliaMath/AbstractFFTs.jl/pull/29, so I guess it would not hurt to polish the code some more and fully integrate it with the philosophy of https://github.com/JuliaMath/AbstractFFTs.jl. PR #85 is a first attempt in this direction.

From my point of view, it would be helpful to move the existing `fftBigFloat` Code into a separate package, say `GenericFFT` and continue polishing it there. It does not really depend on anything else in here and thus moving it to a different package would make depending on the generic FFT  code from the Julia ecosystem easier and more lightweight. I'm happy to make the first steps in this direction if the maintainers of this package agree, but I'm also happy to hear other opinions :smile:.

**Comment by dlfivefifty** [comment]
I think we definitely support this!

**Comment by MikaelSlevinsky** [comment]
Looking at the links you provided, I believe that this package’s FFT’s should ultimately be deprecated in favour of https://github.com/JuliaComputing/FourierTransforms.jl Those look like they are generically written (and create micro-kernels for more prime factors), though it might take a hacking session to make it work for one’s needs.

**Comment by mfherbst** [comment]
Thanks for that pointer! I fully agree and I was not yet aware of this project. Definitely what I had in mind and what I was looking for! I'll take a look.
