### ISSUE TITLE
Fix build on vanilla Julia 

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastTransforms.jl#90]
FastTransforms v0.7 had to be merged manually https://github.com/JuliaRegistries/General/pull/5140

The issue is that the build is failing on a "vanilla" Julia complaining about `cblas.h`: 

https://github.com/JuliaRegistries/General/pull/5140/checks?check_run_id=293234513#step:5:156

I'm afraid this will impact all dependent packages, which will be a nightmare for tagging.

**Comment by MikaelSlevinsky** [comment]
I saw this issue and I agree.

I think if `using CompilerSupportLibraries_jll` gets fixed, then all dependencies should be locatable.

**Comment by MikaelSlevinsky** [comment]
Alternatively, the threading model in the C library could be changed from OpenMP to pthreads to remove the `libgomp` dep. This may be less portable and a bit more complicated than the OpenMP #pragma's.

**Comment by MikaelSlevinsky** [comment]
I think I found a way forward (that will not depend on Julia v1.3+). XGBoost copies `libgomp` from the cross-compiler to the destination lib/bin directory! https://github.com/JuliaPackaging/Yggdrasil/blob/4cacbf2377730f60255500b4e7dd58d9f9c18752/X/XGBoost/build_tarballs.jl#L49

Cross-compiling locally looks promising!
